# permissions for end users to view agents.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: agent-viewer-role
rules:
- apiGroups:
  - azdevops.gofound.nl
  resources:
  - agents
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - azdevops.gofound.nl
  resources:
  - agents/status
  verbs:
  - get
