apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  name: azdevops-agent-operator.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: Agent is the Schema for the agents API
      displayName: Agent
      kind: Agent
      name: agents.azdevops.gofound.nl
      version: v1alpha1
  description: Azure Devops self-hosted agent operator
  displayName: azdevops-agent
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - azure-devops
  - self-hosted-agent
  links:
  - name: Azdevops Agent Operator
    url: https://azdevops-agent-operator.domain
  maturity: alpha
  provider:
    name: gofound
    url: https://github.com/bartvanbenthem/azdevops-agent-operator
  version: 0.0.0
