apiVersion: azdevops.gofound.nl/v1alpha1
kind: Agent
metadata:
  name: agent-sample
spec:
  size: 2
  image: # image: mcr.microsoft.com/azure-pipelines/vsts-agent:ubuntu-16.04
  pool:
    url: https://dev.azure.com/ProjectName
    token: exampleo4m6uekbfpodresprxcsa3fx4xduvkzvmojx
    poolName: operator-sh
    agentName: agent-sample
    workDir:
  proxy:
    httpProxy: 
    httpsProxy:
    ftpProxy: 
    noProxy:
  mtuValue:
  configMap:
