apiVersion: azdevops.gofound.nl/v1alpha1
kind: Agent
metadata:
  name: agent-sample
spec:
  size: 2
  image: # image: bartvanbenthem/agent:v0.0.1
  pool:
    url: https://dev.azure.com/ProjectName
    token: exampleo4m6uekbfpodresprxcsa3fx4xduvkzvmojx
    poolName: operator-sh
    agentName: agent-sample
    workDir:
  proxy:
    httpProxy: http://proxy_server:port
    httpsProxy: https://proxy_server:port
    ftpProxy: http://proxy_server:port
    noProxy:
  mtuValue:
  configMap:
